// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(PetDb))]
    [Migration("20250405224225_VirtualUpdates")]
    partial class VirtualUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ColorOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ColorOptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe0b4683-f7f9-432d-8f14-a685d3e73e71"),
                            Color = "Red",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("af4acbd3-6789-4dd5-8afa-710ca93b0077"),
                            Color = "Orange",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("6513a135-199e-4613-8ea7-12c296e6d217"),
                            Color = "Yellow",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("5b0a3fc3-eebb-4713-ae3d-c846b00821cd"),
                            Color = "Green",
                            Order = 4
                        },
                        new
                        {
                            Id = new Guid("c35af576-e2f0-4835-8f81-ff80c68fa202"),
                            Color = "Blue",
                            Order = 5
                        },
                        new
                        {
                            Id = new Guid("ea75a4cc-15be-46c3-a6bc-514d609ee777"),
                            Color = "Indigo",
                            Order = 6
                        },
                        new
                        {
                            Id = new Guid("d3f928a2-ae05-4eff-a68f-06fa4d7963e9"),
                            Color = "Violet",
                            Order = 7
                        },
                        new
                        {
                            Id = new Guid("add6e376-c3b5-45d2-9ef2-2eca3bbc8b79"),
                            Color = "Pink",
                            Order = 8
                        });
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TagTransaction", b =>
                {
                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagsId", "TransactionsId");

                    b.HasIndex("TransactionsId");

                    b.ToTable("TagTransaction");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.HasOne("ColorOption", "Color")
                        .WithMany("Tags")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");
                });

            modelBuilder.Entity("TagTransaction", b =>
                {
                    b.HasOne("Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ColorOption", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
