import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-tags',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './tags.component.html',
  styleUrl: './tags.component.scss',
})
export class TagsComponent {
  mockTransactions = [
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -59.99,
      category: ['Shopping', 'Electronics'],
      category_id: '19002000',
      date: '2025-03-22',
      location: {
        address: '123 Electronics Blvd',
        city: 'San Francisco',
        country: 'US',
        lat: 37.7749,
        lon: -122.4194,
        store_number: '101',
      },
      name: 'Best Buy',
      merchant_name: 'Best Buy',
      transaction_id: 'txn_1A2B3C4D5E6F7G8H9I0J',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '5732',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -59.99,
      category: ['Shopping', 'Electronics'],
      category_id: '19002000',
      date: '2025-03-22',
      location: {
        address: '123 Electronics Blvd',
        city: 'San Francisco',
        country: 'US',
        lat: 37.7749,
        lon: -122.4194,
        store_number: '101',
      },
      name: 'Best Buy',
      merchant_name: 'Best Buy',
      transaction_id: 'txn_1A2B3C4D5E6F7G8H9I0J',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '5732',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -59.99,
      category: ['Shopping', 'Electronics'],
      category_id: '19002000',
      date: '2025-03-22',
      location: {
        address: '123 Electronics Blvd',
        city: 'San Francisco',
        country: 'US',
        lat: 37.7749,
        lon: -122.4194,
        store_number: '101',
      },
      name: 'Best Buy',
      merchant_name: 'Best Buy',
      transaction_id: 'txn_1A2B3C4D5E6F7G8H9I0J',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '5732',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -59.99,
      category: ['Shopping', 'Electronics'],
      category_id: '19002000',
      date: '2025-03-22',
      location: {
        address: '123 Electronics Blvd',
        city: 'San Francisco',
        country: 'US',
        lat: 37.7749,
        lon: -122.4194,
        store_number: '101',
      },
      name: 'Best Buy',
      merchant_name: 'Best Buy',
      transaction_id: 'txn_1A2B3C4D5E6F7G8H9I0J',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '5732',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -59.99,
      category: ['Shopping', 'Electronics'],
      category_id: '19002000',
      date: '2025-03-22',
      location: {
        address: '123 Electronics Blvd',
        city: 'San Francisco',
        country: 'US',
        lat: 37.7749,
        lon: -122.4194,
        store_number: '101',
      },
      name: 'Best Buy',
      merchant_name: 'Best Buy',
      transaction_id: 'txn_1A2B3C4D5E6F7G8H9I0J',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '5732',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -59.99,
      category: ['Shopping', 'Electronics'],
      category_id: '19002000',
      date: '2025-03-22',
      location: {
        address: '123 Electronics Blvd',
        city: 'San Francisco',
        country: 'US',
        lat: 37.7749,
        lon: -122.4194,
        store_number: '101',
      },
      name: 'Best Buy',
      merchant_name: 'Best Buy',
      transaction_id: 'txn_1A2B3C4D5E6F7G8H9I0J',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '5732',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -59.99,
      category: ['Shopping', 'Electronics'],
      category_id: '19002000',
      date: '2025-03-22',
      location: {
        address: '123 Electronics Blvd',
        city: 'San Francisco',
        country: 'US',
        lat: 37.7749,
        lon: -122.4194,
        store_number: '101',
      },
      name: 'Best Buy',
      merchant_name: 'Best Buy',
      transaction_id: 'txn_1A2B3C4D5E6F7G8H9I0J',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '5732',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -59.99,
      category: ['Shopping', 'Electronics'],
      category_id: '19002000',
      date: '2025-03-22',
      location: {
        address: '123 Electronics Blvd',
        city: 'San Francisco',
        country: 'US',
        lat: 37.7749,
        lon: -122.4194,
        store_number: '101',
      },
      name: 'Best Buy',
      merchant_name: 'Best Buy',
      transaction_id: 'txn_1A2B3C4D5E6F7G8H9I0J',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '5732',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -59.99,
      category: ['Shopping', 'Electronics'],
      category_id: '19002000',
      date: '2025-03-22',
      location: {
        address: '123 Electronics Blvd',
        city: 'San Francisco',
        country: 'US',
        lat: 37.7749,
        lon: -122.4194,
        store_number: '101',
      },
      name: 'Best Buy',
      merchant_name: 'Best Buy',
      transaction_id: 'txn_1A2B3C4D5E6F7G8H9I0J',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '5732',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -35.5,
      category: ['Food & Drink', 'Restaurants'],
      category_id: '13005000',
      date: '2025-03-20',
      location: {
        address: '7890 Pine Ave',
        city: 'Chicago',
        country: 'US',
        lat: 41.8781,
        lon: -87.6298,
        store_number: '001',
      },
      name: 'Pizza Hut',
      merchant_name: 'Pizza Hut',
      transaction_id: 'txn_2B3C4D5E6F7G8H9I0J1K',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '5812',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -300.0,
      category: ['Transportation', 'Car Rental'],
      category_id: '18001000',
      date: '2025-03-18',
      location: {
        address: '4567 Highway 1',
        city: 'Los Angeles',
        country: 'US',
        lat: 34.0522,
        lon: -118.2437,
        store_number: '310',
      },
      name: 'Enterprise Rent-A-Car',
      merchant_name: 'Enterprise Rent-A-Car',
      transaction_id: 'txn_3C4D5E6F7G8H9I0J1K2L',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '7512',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -9.99,
      category: ['Entertainment', 'Streaming Services'],
      category_id: '18001000',
      date: '2025-03-15',
      location: null,
      name: 'Spotify Subscription',
      merchant_name: 'Spotify',
      transaction_id: 'txn_4D5E6F7G8H9I0J1K2L3M',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '7922',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -12.5,
      category: ['Food & Drink', 'Coffee & Snacks'],
      category_id: '13003000',
      date: '2025-03-14',
      location: {
        address: '6789 Coffee St',
        city: 'Chicago',
        country: 'US',
        lat: 41.8781,
        lon: -87.6298,
        store_number: '017',
      },
      name: 'Starbucks',
      merchant_name: 'Starbucks',
      transaction_id: 'txn_5E6F7G8H9I0J1K2L3M4N',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '5814',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: 1500.0,
      category: ['Income'],
      category_id: '20000000',
      date: '2025-03-10',
      location: null,
      name: 'Direct Deposit',
      merchant_name: 'Acme Corp',
      transaction_id: 'txn_6F7G8H9I0J1K2L3M4N5O',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'credit',
      payment_channel: 'direct deposit',
      account_owner: 'John Doe',
      merchant_category_code: '0000',
    },
    {
      account_id: '6fbf1e4d-4bfb-4f2b-a8c9-d65e5280d496',
      amount: -499.99,
      category: ['Shopping', 'Electronics'],
      category_id: '19002000',
      date: '2025-03-01',
      location: {
        address: '123 Electronics Blvd',
        city: 'San Francisco',
        country: 'US',
        lat: 37.7749,
        lon: -122.4194,
        store_number: '200',
      },
      name: 'Apple Store',
      merchant_name: 'Apple Store',
      transaction_id: 'txn_7G8H9I0J1K2L3M4N5O6P',
      pending: false,
      pending_transaction_id: null,
      transaction_type: 'debit',
      payment_channel: 'card',
      account_owner: 'John Doe',
      merchant_category_code: '5734',
    },
  ];
}
